
let separator_prefix = "write(1, \""
let read_prefix = "read(3, \""
let write_prefix = "write(3, \""

let startswith prefix s =
  let prefix' = String.length prefix and s' = String.length s in
  prefix' <= s' && (String.sub s 0 prefix' = prefix)

let rest prefix s =
  let prefix' = String.length prefix in
  String.sub s prefix' (String.length s - prefix')

let trim s =
  let i = String.rindex s '"' in
  String.sub s 0 i

let _ =
  let reading = ref [] in
  let writing = ref [] in
  let write_desc = ref "" in
  Printf.printf "(* This file is autogenerated *)\n";
  Printf.printf "let all = [\n";
while true do
  try
  let l = input_line stdin in
  if startswith separator_prefix l then begin
    if !write_desc = "" then begin
      write_desc := trim (rest separator_prefix l);
    end else begin
      let read_desc = trim (rest separator_prefix l) in
      let r = String.concat "" (List.rev !reading) in
      let w = String.concat "" (List.rev !writing) in
      Printf.printf "\"%s\", \"%s\", \n\"%s\", \"%s\";\n" !write_desc w read_desc r;
      write_desc := "";
      reading := [];
      writing := [];
    end
  end else if startswith read_prefix l then begin
    reading := trim (rest read_prefix l) :: !reading
  end else if startswith write_prefix l then begin
    writing := trim (rest write_prefix l) :: !writing
  end
  with End_of_file ->
    Printf.printf "]\n";
    exit 0
done
